# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
- oraclejdk11
- openjdk11
# используем режим обычного пользователя для сборки проекта.
sudo: false

services:
- postgresql

before_install:
- psql -c 'create database police;' -U postgres

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту MorozovRoman.88@mail.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - MorozovRoman.88@mail.ru
    on_success: never # default: change
    on_failure: always # default: always